name: Build & Test PrettyBlazor
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.101
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
